Repository GSG-G7/lang-mate, pull requests merged in 2019-09, with the labels that each got.

#13 fix readme file to update the user journey
  README.md
Labels: Merge

#19 Add tech-stack, team members, database schema and prototype
  README.md
Labels: For-Merge

#35 react file structure
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.js
  client/src/App.sass
  client/src/App.test.js
  client/src/components/Login/index.js
  client/src/components/Login/index.sass
  client/src/components/commonComponents/Button/index.js
  client/src/components/commonComponents/Button/index.sass
  client/src/components/commonComponents/Checkbox/index.js
  client/src/components/commonComponents/Checkbox/index.sass
  client/src/components/commonComponents/Dropdown/index.js
  client/src/components/commonComponents/Dropdown/index.sass
  client/src/components/commonComponents/Input/index.js
  client/src/components/commonComponents/Input/index.sass
  client/src/components/commonComponents/MessageCard/index.js
  client/src/components/commonComponents/MessageCard/index.sass
  client/src/components/commonComponents/UserCard/index.js
  client/src/components/commonComponents/UserCard/index.sass
  client/src/components/pages/Chat/index.js
  client/src/components/pages/Chat/index.sass
  client/src/components/pages/Home/Filter/index.js
  client/src/components/pages/Home/Filter/index.sass
  client/src/components/pages/Home/Messages/index.js
  client/src/components/pages/Home/Messages/index.sass
  client/src/components/pages/Home/People/index.js
  client/src/components/pages/Home/People/index.sass
  client/src/components/pages/Home/index.js
  client/src/components/pages/Landing/index.js
  client/src/components/pages/Landing/index.sass
  client/src/components/pages/Profile/index.js
  client/src/components/pages/Profile/index.sass
  client/src/components/pages/Settings/index.js
  client/src/components/pages/Settings/index.sass
  client/src/components/pages/Signup/index.js
  client/src/components/pages/Signup/index.sass
  client/src/index.js
  client/src/index.sass
  client/src/routers/index.js
Labels: For-Merge, Setup

#36 backend structure
  server/app.js
  server/controllers/auth/authentication.js
  server/controllers/auth/index.js
  server/controllers/auth/login.js
  server/controllers/auth/logout.js
  server/controllers/auth/signup.js
  server/controllers/error.js
  server/controllers/index.js
  server/controllers/users/getUser.js
  server/controllers/users/index.js
  server/controllers/users/updateUser.js
  server/helpers/validationSchema.js
  server/index.js
  server/models/config/build.js
  server/models/config/connection.js
  server/models/config/db_build.sql
  server/models/config/insertFakeData.sql
  server/models/queries/index.js
  server/routes/index.js
  test/index.test.js
  test/models.test.js
  test/routes.test.js
Labels: For-Merge

#37 npm init
  .gitignore
  client/src/App.test.js
  client/src/index.js
  package-lock.json
  package.json
  server/app.js
  server/index.js
  server/routes/index.js
Labels: Configuration, For-Merge, Setup

#52 Travis Ci
  .travis.yml
  test/index.test.js
Labels: For-Merge, Setup

#56 init project with proxy and concurrently
  client/.eslintrc.js
  client/package.json
  client/src/App.js
  client/src/components/pages/Settings/index.css
  package-lock.json
  package.json
  server/app.js
  server/routes/index.js
Labels: For-Merge

#54 user card
  client/package.json
  client/src/components/commonComponents/UserCard/index.css
  client/src/components/commonComponents/UserCard/index.js
  package-lock.json
Labels: Common, Component, For-Merge, Frontend

#58 button component
  client/src/components/commonComponents/Button/index.js
Labels: For-Merge

#59 47 back button
  client/src/components/commonComponents/BackButton/index.css
  client/src/components/commonComponents/BackButton/index.js
Labels: For Merge

#53 Input Component
  .gitignore
  client/package-lock.json
  client/src/App.css
  client/src/components/commonComponents/Input/index.css
  client/src/components/commonComponents/Input/index.js
Labels: Common, Component, For Merge

#65 setup project
  client/src/App.js
  client/src/components/common/BackButton/index.css
  client/src/components/common/BackButton/index.js
  client/src/components/common/Button/index.css
  client/src/components/common/Button/index.js
  client/src/components/common/Checkbox/index.css
  client/src/components/common/Checkbox/index.js
  client/src/components/common/Dropdown/index.css
  client/src/components/common/Dropdown/index.js
  client/src/components/common/Input/index.css
  client/src/components/common/Input/index.js
  client/src/components/common/MessageCard/index.css
  client/src/components/common/MessageCard/index.js
  client/src/components/common/UserCard/index.css
  client/src/components/common/UserCard/index.js
  client/src/services/api.js
  server/database/config/dbbuild.js
  server/database/config/dbbuild.sql
  server/database/config/dbconnection.js
  server/database/config/insertFakeData.sql
  server/database/queries/index.js
Labels: For Merge

#60 code checkbox component
  client/src/components/commonComponents/Checkbox/index.css
  client/src/components/commonComponents/Checkbox/index.js
Labels: Component, Frontend, In progress

#55 DropDowm
  .gitignore
  client/src/components/common/Dropdown/index.css
  client/src/components/common/Dropdown/index.js
Labels: Common, Component, For Merge

#69 Avatar
  client/src/components/common/Avatar/index.css
  client/src/components/common/Avatar/index.js
Labels: Common, Component, For Merge

#68 db configuration done
  server/database/config/dbbuild.js
  server/database/config/dbconnection.js
Labels: Backend, DB, For Merge

#73 moved the paths out of the UserMenu
  client/src/components/assets/svgPaths.js
  client/src/components/common/UserMenu/index.js
Labels: Awaiting Review, Common, Component, Frontend

#66 checkbox common commponent
  client/src/components/common/Checkbox/index.css
  client/src/components/common/Checkbox/index.js
Labels: Awaiting Review, Common, Component, Frontend

#74 20 backend routes
  package.json
  server/controllers/auth/index.js
  server/controllers/auth/login.js
  server/controllers/auth/logout.js
  server/controllers/auth/signup.js
  server/controllers/errors/error.js
  server/controllers/errors/index.js
  server/controllers/index.js
  server/controllers/interests/getInterest.js
  server/controllers/interests/index.js
  server/controllers/languages/index.js
  server/controllers/languages/language.js
  server/controllers/messages/addChannel.js
  server/controllers/messages/getChannelMessages.js
  server/controllers/messages/index.js
  server/controllers/users/changePassword.js
  server/controllers/users/deactivateUser.js
  server/controllers/users/getUserByInterest.js
  server/controllers/users/getUserChannels.js
  server/controllers/users/getUserInfo.js
  server/controllers/users/getUsersByLang.js
  server/controllers/users/index.js
  server/controllers/users/searchUser.js
  server/database/queries/auth/index.js
  server/database/queries/auth/login.js
  server/database/queries/auth/logout.js
  server/database/queries/auth/signup.js
  server/database/queries/interests/getInterest.js
  server/database/queries/interests/index.js
  server/database/queries/languages/index.js
  server/database/queries/languages/language.js
  server/database/queries/messages/addChannel.js
  server/database/queries/messages/getChannelMessages.js
  server/database/queries/messages/index.js
  server/database/queries/users/changePassword.js
  server/database/queries/users/deactivateUser.js
  server/database/queries/users/getUserByInterest.js
  server/database/queries/users/getUserChannels.js
  server/database/queries/users/getUserInfo.js
  server/database/queries/users/getUsersByLang.js
  server/database/queries/users/index.js
  server/database/queries/users/searchUser.js
  server/routes/index.js
Labels: Awaiting Review, Backend

#76 Backend Routes
  server/routes/index.js
Labels: Awaiting Review, Backend

#78 GET /api/v1/languages
  .travis.yml
  server/controllers/languages/index.js
  server/controllers/languages/language.js
  server/database/config/dbbuild.js
  server/database/queries/languages/getLanguages.js
  server/database/queries/languages/index.js
  test/queries/index.test.js
  test/queries/languages.test.js
  test/routes/index.test.js
  test/routes/languages.test.js
Labels: Awaiting Review, Backend, Routes, query, testing

#80 Fixes in setup
  server/app.js
  server/database/config/fakedata.sql
  server/database/queries/interests/getInterests.js
  server/database/queries/messages/addChannel.js
  server/database/queries/messages/getChannelMessages.js
  server/database/queries/users/addUser.js
  server/database/queries/users/changePassword.js
  server/database/queries/users/deactivateUser.js
  server/database/queries/users/getUserChannels.js
  server/database/queries/users/getUserInfo.js
  server/database/queries/users/getUsersByInterest.js
  server/database/queries/users/getUsersByLang.js
  server/database/queries/users/searchUsers.js
Labels: Setup, bug

#81 Users By Interest
  server/controllers/users/getUserByInterest.js
  server/controllers/users/getUsersByInterest.js
  server/controllers/users/index.js
  server/database/queries/languages/getLanguageById.js
  server/database/queries/languages/index.js
  server/database/queries/users/getUsersByInterest.js
  server/helpers/formatLanguages.js
  server/routes/index.js
  test/index.test.js
  test/queries/getUsersByInterest.test.js
  test/queries/index.test.js
  test/queries/languages.test.js
  test/routes/index.test.js
  test/routes/languages.test.js
  test/routes/usersByInterest.test.js
Labels: Awaiting Review

#88 38 auth middleware
  server/controllers/auth/authentication.js
  server/helpers/jwtVerifyPromise.js
Labels: Awaiting Review

#79 24 channels username
  server/controllers/errors/error.js
  server/controllers/messages/getChannelMessages.js
  server/controllers/users/getUsersByInterest.js
  server/database/queries/messages/getChannelMessages.js
  server/database/queries/messages/index.js
  test/queries/getChannelMessages.test.js
  test/queries/index.test.js
  test/routes/getChannelMessages.test.js
  test/routes/index.test.js
Labels: For Merge

#92 language change test to remove nested promise
  package.json
  test/queries/languages.test.js
Labels: For Merge

#82 change password PUT /api/v1/users/change-password
  server/controllers/users/changePassword.js
  server/database/config/fakedata.sql
  server/database/queries/users/changePassword.js
  test/queries/changePassword.test.js
  test/queries/index.test.js
  test/routes/changePassword.test.js
  test/routes/index.test.js
Labels: For Merge

#86 28 login
  server/controllers/auth/login.js
  server/helpers/index.js
  server/helpers/jwtSignPromise.js
Labels: For Merge

#93 logout done
  server/controllers/auth/logout.js
  test/routes/index.test.js
  test/routes/logout.test.js
Labels: Awaiting Review

#98 language 'edit to be more clear'
  server/controllers/languages/language.js
  test/queries/languages.test.js
Labels: Awaiting Review

#96 add channel and add subscribers
  server/controllers/messages/addChannel.js
  server/controllers/messages/getChannels.js
  server/controllers/messages/index.js
  server/database/queries/messages/addChannel.js
  server/database/queries/messages/getChannels.js
  server/database/queries/messages/index.js
  server/helpers/validateAddChannel.js
  server/routes/index.js
  test/queries/addChannel.test.js
  test/queries/getChannels.test.js
  test/queries/index.test.js
  test/routes/addChannel.test.js
  test/routes/getChannels.test.js
  test/routes/index.test.js
Labels: Awaiting Review

#87 All Interests
  server/controllers/interests/getInterest.js
  server/database/queries/interests/getInterests.js
  server/database/queries/interests/index.js
  test/queries/getInterests.test.js
  test/queries/index.test.js
  test/routes/getInterests.test.js
  test/routes/index.test.js
Labels: Awaiting Review

#83 27 signup route
  package-lock.json
  server/app.js
  server/controllers/auth/signup.js
  server/controllers/auth/validation/signup-validation.js
  server/controllers/users/getUsersByInterest.js
  server/database/queries/index.js
  server/database/queries/users/addUser.js
  server/database/queries/users/addUserInterests.js
  server/database/queries/users/getUserInfo.js
  server/database/queries/users/index.js
  server/helpers/index.js
  test/queries/addUser.test.js
  test/queries/index.test.js
  test/routes/index.test.js
  test/routes/signup.test.js
Labels: Awaiting Review

#94 25 search users
  server/controllers/users/index.js
  server/controllers/users/searchUser.js
  server/controllers/users/searchUsers.js
  server/database/queries/users/searchUsers.js
  server/helpers/formatLanguagesV2.js
  server/helpers/index.js
  server/routes/index.js
  test/queries/index.test.js
  test/queries/searchUsers.test.js
  test/routes/index.test.js
  test/routes/searchUsers.test.js
Labels: For Merge

#104 Auth Middleware
  server/controllers/auth/index.js
  server/controllers/users/changePassword.js
  server/routes/index.js
  test/routes/addChannel.test.js
  test/routes/changePassword.test.js
  test/routes/cookie.test.js
  test/routes/getChannelMessages.test.js
  test/routes/getChannels.test.js
  test/routes/getInterests.test.js
  test/routes/languages.test.js
  test/routes/logout.test.js
  test/routes/searchUsers.test.js
  test/routes/usersByInterest.test.js
Labels: Awaiting Review

#85 Deactivate
  server/controllers/users/deactivateUser.js
  server/database/queries/users/deactivateUser.js
  test/queries/deactivate.test.js
  test/queries/index.test.js
  test/routes/deactivate.test.js
  test/routes/index.test.js
Labels: Awaiting Review

#95 Users By Native Language
  server/controllers/users/getUsersByLang.js
  server/database/queries/users/getUsersByLang.js
  test/queries/getUsersByLang.test.js
  test/queries/index.test.js
  test/routes/getUsersByLang.test.js
  test/routes/index.test.js
Labels: Awaiting Review, Backend

#109 Refactor Users By Interest
  server/controllers/users/getUsersByInterest.js
Labels: Awaiting Review

#103 rehandled errors accordingly
  server/controllers/auth/authentication.js
  server/controllers/auth/login.js
  server/controllers/auth/signup.js
  server/controllers/users/changePassword.js
  server/controllers/users/searchUsers.js
Labels: Awaiting Review

#100 added that if the user signs
  server/controllers/auth/login.js
  server/controllers/auth/signup.js
  server/database/queries/users/index.js
  server/database/queries/users/reactivateUser.js
  test/routes/login.test.js
Labels: Awaiting Review

#113 Under Construction
  client/src/components/pages/UnderConstruction/index.css
  client/src/components/pages/UnderConstruction/index.js
Labels: Component, Frontend

#114 React Routes
  client/src/App.js
  client/src/components/pages/Chat/index.js
  client/src/components/pages/Home/index.css
  client/src/components/pages/Home/index.js
  client/src/components/pages/Landing/index.js
  client/src/components/pages/Login/index.js
  client/src/components/pages/Profile/index.js
  client/src/components/pages/Settings/index.js
  client/src/components/pages/Signup/index.js
Labels: For Merge, Frontend

#111 Landing page
  client/src/App.css
  client/src/App.js
  client/src/components/assets/study-group.jpg
  client/src/components/assets/svgPaths.js
  client/src/components/common/Button/index.js
  client/src/components/pages/Landing/index.css
  client/src/components/pages/Landing/index.js
Labels: Awaiting Review, Component, Frontend

#117 changed return next to throw next
  server/controllers/auth/authentication.js
  server/controllers/auth/login.js
  server/controllers/auth/signup.js
  server/controllers/users/changePassword.js
  server/controllers/users/getUsersByInterest.js
  server/controllers/users/getUsersByLang.js
  server/controllers/users/searchUsers.js
Labels: Awaiting Review
