Repository GSG-G7/lang-mate, pull requests merged in 2019-10, with the labels that each got.

#110 18 login page
  client/package-lock.json
  client/src/App.js
  client/src/components/common/BackButton/index.js
  client/src/components/common/Input/index.css
  client/src/components/common/Input/index.js
  client/src/components/pages/Login/index.css
  client/src/components/pages/Login/index.js
  client/src/services/api.js
  package-lock.json
  server/controllers/errors/error.js
  test/routes/searchUsers.test.js
Labels: Awaiting Review

#122 119 channel username
  server/controllers/users/getUserChannels.js
  server/database/queries/messages/getChaMessagesByChaId.js
  server/database/queries/messages/index.js
  server/database/queries/users/getUserChannels.js
  server/helpers/formatLanguages.js
  server/helpers/formatMessages.js
  server/helpers/index.js
  server/routes/index.js
Labels: Awaiting Review

#126 React Auth
  client/src/App.js
  client/src/components/Auth/PrivateRoute.js
  client/src/components/Auth/auth.js
  client/src/components/pages/Login/index.js
  client/src/services/api.js
  server/controllers/auth/index.js
  server/controllers/auth/isAuth.js
  server/controllers/auth/login.js
  server/routes/index.js
Labels: Auth, In progress

#128 got the interests, languages routes before the auth middleware
  server/routes/index.js
  test/routes/getInterests.test.js
  test/routes/languages.test.js
Labels: Awaiting Review

#132 React Auth
  client/src/App.js
  client/src/components/Auth/PrivateRoute.js
  client/src/components/Auth/auth.js
  client/src/components/pages/Login/index.js
Labels: Auth, Awaiting Review

#135 added interests to the user route by username
  server/controllers/users/getUserInfo.js
Labels: Awaiting Review

#130 Chat
  client/src/components/common/Input/index.css
  client/src/components/pages/Chat/index.css
  client/src/components/pages/Chat/index.js
Labels: Frontend, In progress

#118 signup page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Auth/PrivateRoute.js
  client/src/components/common/Checkbox/index.css
  client/src/components/common/Checkbox/index.js
  client/src/components/common/Dropdown/index.js
  client/src/components/common/Input/index.js
  client/src/components/pages/Login/index.js
  client/src/components/pages/Signup/index.css
  client/src/components/pages/Signup/index.js
  client/src/components/pages/utils/signupValidation.js
  client/src/services/api.js
  server/controllers/auth/signup.js
  server/controllers/auth/validation/signup-validation.js
  server/routes/index.js
Labels: Frontend, In progress

#120 Home page (main feed)
  client/src/App.js
  client/src/components/assets/svgPaths.js
  client/src/components/common/MessageCard/index.css
  client/src/components/common/MessageCard/index.js
  client/src/components/common/UserCard/index.css
  client/src/components/common/UserCard/index.js
  client/src/components/common/UserMenu/index.css
  client/src/components/common/UserMenu/index.js
  client/src/components/pages/Chat/index.css
  client/src/components/pages/Chat/index.js
  client/src/components/pages/Home/Messages/index.js
  client/src/components/pages/Home/People/index.css
  client/src/components/pages/Home/People/index.js
  client/src/components/pages/Home/index.css
  client/src/components/pages/Home/index.js
  client/src/components/pages/Profile/index.js
  client/src/services/api.js
  client/src/services/date.js
  server/app.js
Labels: Awaiting Review, Frontend
